# To get this to work on spin, launch the docker-compose.yml.init version first, and follow the instructions
# to change permissions on /var/jenkins_home.

version: '2'

services:
    app: #camunda is not an allowed service name. Allowed service names are: api,db,kv,lb,web,app
        #image: jenkins/jenkins:lts
        image: jenkinsci/blueocean
        restart: always
        cap_drop:
         - ALL
        cap_add:
         - CHOWN
         - DAC_OVERRIDE
         - FOWNER
         - SETGID
         - SETUID
#        user: 5951:5242
        ports:
         - 60010:8080
         - 60011:50000
        volumes:
         - app.jgi-pps-jenkins:/var/jenkins_home
         - app.jgi-pps-jenkins:/usr/share/jenkins
         - app.jgi-pps-jenkins:/usr/share/jenkins/ref
volumes:
    app.jgi-pps-jenkins:
        driver: rancher-nfs
        external: true
