#
# to use this template, substitute the following throughout:
#
# - for camunda: your stack name
# - for PostgresUser: your Postgres user name
# - for ProjectDir: your global file system project directory
# - for UserID: your numeric user ID that should own the dump files
# - for GroupID: your numeric group ID that should own the dump files

version: '2'

services:
    app: #camunda is not an allowed service name. Allowed service names are: api,db,kv,lb,web,app
        image: debian:latest
        cap_drop:
         - ALL
        cap_add:
         - CHOWN
         - DAC_OVERRIDE
         - FOWNER
         - SETGID
         - SETUID
        stdin_open: true
        tty: true
        volumes:
         - app.jgi-pps-jenkins:/var/jenkins_home
volumes:
    app.jgi-pps-jenkins:
        driver: rancher-nfs
        external: true
